name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you so much for contributing to Vaporizer2, Your help is highly appreciated!"
        pr-message: "Thank you so much for contributing to Vaporizer2, Your help is highly appreciated!"
